import {
  SyncConflictPolicy,
  SyncConflictPolicyValue,
} from "@/shared/sync/types/syncConflict.types";
import { SyncRegistryItem } from "../types/sync.entity.types";
import { SyncTombstonePolicy } from "../types/sync.constant";
import { syncDependencyOrder } from "./syncDependencyOrder";

const directSyncFields = {
  syncStatusField: "sync_status",
  deletedAtField: "deleted_at",
  remoteIdField: "remote_id",
  lastSyncedAtField: "last_synced_at",
} as const;

export const deviceLocalOnlyTables = [
  "app_settings",
  "user_management_permissions",
] as const;

export const sensitiveSyncExcludedTables = [
  "auth_credentials",
  "auth_users",
] as const;

export const supportUploadTables = ["bug_reports", "app_ratings"] as const;

const createRegistryItem = (
  item: SyncRegistryItem,
): SyncRegistryItem => ({
  supportsDirectStatusTracking: true,
  ...directSyncFields,
  ...item,
});

export const syncRegistry: readonly SyncRegistryItem[] = [
  createRegistryItem({
    tableName: "accounts",
    entityName: "Account",
    scopeField: "remote_id",
    dependsOn: [],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
  }),
  createRegistryItem({
    tableName: "business_profiles",
    entityName: "BusinessProfile",
    scopeField: "account_remote_id",
    dependsOn: ["accounts"],
    conflictPolicy: SyncConflictPolicy.ClientWins,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
    remoteIdField: "account_remote_id",
  }),
  createRegistryItem({
    tableName: "account_members",
    entityName: "AccountMember",
    scopeField: "account_remote_id",
    dependsOn: ["accounts"],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
  }),
  createRegistryItem({
    tableName: "account_roles",
    entityName: "AccountRole",
    scopeField: "account_remote_id",
    dependsOn: ["accounts"],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
  }),
  createRegistryItem({
    tableName: "account_role_permissions",
    entityName: "AccountRolePermission",
    scopeField: "role_remote_id",
    dependsOn: ["account_roles"],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.AppendOnly,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
    supportsDirectStatusTracking: false,
    syncStatusField: undefined,
    deletedAtField: undefined,
    remoteIdField: undefined,
    lastSyncedAtField: undefined,
    compositeRemoteIdFields: ["role_remote_id", "permission_code"],
    scopeJoin: {
      parentTable: "account_roles",
      parentJoinField: "remote_id",
      childJoinField: "role_remote_id",
      parentScopeField: "account_remote_id",
      parentDeletedAtField: "deleted_at",
    },
  }),
  createRegistryItem({
    tableName: "account_user_roles",
    entityName: "AccountUserRole",
    scopeField: "account_remote_id",
    dependsOn: ["account_members", "account_roles"],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.AppendOnly,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
    supportsDirectStatusTracking: false,
    syncStatusField: undefined,
    deletedAtField: undefined,
    remoteIdField: undefined,
    lastSyncedAtField: undefined,
    compositeRemoteIdFields: [
      "account_remote_id",
      "user_remote_id",
      "role_remote_id",
    ],
  }),
  createRegistryItem({
    tableName: "categories",
    entityName: "Category",
    scopeField: "account_remote_id",
    dependsOn: ["accounts"],
    conflictPolicy: SyncConflictPolicy.ClientWins,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
  }),
  createRegistryItem({
    tableName: "contacts",
    entityName: "Contact",
    scopeField: "account_remote_id",
    dependsOn: ["accounts"],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
  }),
  createRegistryItem({
    tableName: "money_accounts",
    entityName: "MoneyAccount",
    scopeField: "scope_account_remote_id",
    dependsOn: ["accounts"],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
    ignoredPullFields: ["current_balance"],
    protectedFields: ["current_balance"],
  }),
  createRegistryItem({
    tableName: "products",
    entityName: "Product",
    scopeField: "account_remote_id",
    dependsOn: ["accounts", "categories"],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
    ignoredPullFields: ["stock_quantity"],
    protectedFields: ["stock_quantity"],
  }),
  createRegistryItem({
    tableName: "inventory_movements",
    entityName: "InventoryMovement",
    scopeField: "account_remote_id",
    dependsOn: ["products"],
    conflictPolicy: SyncConflictPolicy.ManualReview,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: true,
    protectedFields: [
      "product_remote_id",
      "movement_type",
      "quantity",
      "delta_quantity",
      "unit_rate",
    ],
  }),
  createRegistryItem({
    tableName: "billing_documents",
    entityName: "BillingDocument",
    scopeField: "account_remote_id",
    dependsOn: ["accounts", "contacts"],
    conflictPolicy: SyncConflictPolicy.ManualReview,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: true,
    isWorkflowAggregate: true,
    protectedFields: [
      "status",
      "subtotal_amount",
      "tax_amount",
      "total_amount",
      "linked_ledger_entry_remote_id",
      "contact_remote_id",
    ],
    terminalStatuses: ["pending", "partially_paid", "paid", "overdue"],
  }),
  createRegistryItem({
    tableName: "billing_document_items",
    entityName: "BillingDocumentItem",
    scopeField: "document_remote_id",
    dependsOn: ["billing_documents"],
    conflictPolicy: SyncConflictPolicy.ManualReview,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: true,
    isWorkflowAggregate: false,
    supportsDirectStatusTracking: false,
    syncStatusField: undefined,
    lastSyncedAtField: undefined,
    scopeJoin: {
      parentTable: "billing_documents",
      parentJoinField: "remote_id",
      childJoinField: "document_remote_id",
      parentScopeField: "account_remote_id",
      parentDeletedAtField: "deleted_at",
    },
  }),
  createRegistryItem({
    tableName: "transactions",
    entityName: "Transaction",
    scopeField: "account_remote_id",
    dependsOn: ["money_accounts", "contacts", "ledger_entries"],
    conflictPolicy: SyncConflictPolicy.ManualReview,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: true,
    isWorkflowAggregate: true,
    protectedFields: [
      "amount",
      "direction",
      "transaction_type",
      "settlement_money_account_remote_id",
      "posting_status",
      "source_module",
      "source_remote_id",
      "source_action",
      "idempotency_key",
    ],
  }),
  createRegistryItem({
    tableName: "ledger_entries",
    entityName: "LedgerEntry",
    scopeField: "business_account_remote_id",
    dependsOn: ["accounts", "contacts", "billing_documents"],
    conflictPolicy: SyncConflictPolicy.ManualReview,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: true,
    isWorkflowAggregate: true,
    protectedFields: [
      "amount",
      "balance_direction",
      "linked_transaction_remote_id",
      "linked_document_remote_id",
      "settlement_account_remote_id",
      "due_at",
    ],
  }),
  createRegistryItem({
    tableName: "orders",
    entityName: "Order",
    scopeField: "account_remote_id",
    dependsOn: ["accounts", "contacts"],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: true,
    protectedFields: [
      "status",
      "linked_billing_document_remote_id",
      "linked_ledger_due_entry_remote_id",
      "total_amount",
    ],
    terminalStatuses: ["delivered", "returned", "cancelled"],
  }),
  createRegistryItem({
    tableName: "order_lines",
    entityName: "OrderLine",
    scopeField: "order_remote_id",
    dependsOn: ["orders", "products"],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
    scopeJoin: {
      parentTable: "orders",
      parentJoinField: "remote_id",
      childJoinField: "order_remote_id",
      parentScopeField: "account_remote_id",
      parentDeletedAtField: "deleted_at",
    },
  }),
  createRegistryItem({
    tableName: "pos_sales",
    entityName: "PosSale",
    scopeField: "business_account_remote_id",
    dependsOn: [
      "contacts",
      "products",
      "billing_documents",
      "ledger_entries",
      "transactions",
    ],
    conflictPolicy: SyncConflictPolicy.ManualReview,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: true,
    isWorkflowAggregate: true,
    protectedFields: [
      "receipt_number",
      "workflow_status",
      "cart_lines_snapshot_json",
      "payment_parts_snapshot_json",
      "billing_document_remote_id",
      "ledger_entry_remote_id",
      "posted_transaction_remote_ids_json",
      "grand_total",
    ],
    terminalStatuses: ["posted", "partially_posted"],
  }),
  createRegistryItem({
    tableName: "emi_plans",
    entityName: "EmiPlan",
    scopeField: "business_account_remote_id",
    dependsOn: ["accounts", "money_accounts"],
    conflictPolicy: SyncConflictPolicy.VersionBased,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: true,
    isWorkflowAggregate: true,
  }),
  createRegistryItem({
    tableName: "emi_installments",
    entityName: "EmiInstallment",
    scopeField: "plan_remote_id",
    dependsOn: ["emi_plans"],
    conflictPolicy: SyncConflictPolicy.ManualReview,
    tombstonePolicy: SyncTombstonePolicy.AppendOnly,
    isFinancialRecord: true,
    isWorkflowAggregate: false,
    supportsDirectStatusTracking: false,
    syncStatusField: undefined,
    lastSyncedAtField: undefined,
    scopeJoin: {
      parentTable: "emi_plans",
      parentJoinField: "remote_id",
      childJoinField: "plan_remote_id",
      parentScopeField: "business_account_remote_id",
      parentDeletedAtField: "deleted_at",
    },
  }),
  createRegistryItem({
    tableName: "installment_payment_links",
    entityName: "InstallmentPaymentLink",
    scopeField: "plan_remote_id",
    dependsOn: ["emi_plans", "emi_installments", "transactions"],
    conflictPolicy: SyncConflictPolicy.ManualReview,
    tombstonePolicy: SyncTombstonePolicy.AppendOnly,
    isFinancialRecord: true,
    isWorkflowAggregate: false,
    supportsDirectStatusTracking: false,
    syncStatusField: undefined,
    deletedAtField: undefined,
    remoteIdField: "remote_id",
    lastSyncedAtField: undefined,
    scopeJoin: {
      parentTable: "emi_plans",
      parentJoinField: "remote_id",
      childJoinField: "plan_remote_id",
      parentScopeField: "business_account_remote_id",
      parentDeletedAtField: "deleted_at",
    },
  }),
  createRegistryItem({
    tableName: "budget_plans",
    entityName: "BudgetPlan",
    scopeField: "account_remote_id",
    dependsOn: ["accounts", "categories"],
    conflictPolicy: SyncConflictPolicy.ClientWins,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
  }),
  createRegistryItem({
    tableName: "business_notes",
    entityName: "BusinessNote",
    scopeField: "account_remote_id",
    dependsOn: ["accounts"],
    conflictPolicy: SyncConflictPolicy.ClientWins,
    tombstonePolicy: SyncTombstonePolicy.LocalOnly,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
    supportsDirectStatusTracking: false,
    syncStatusField: undefined,
    deletedAtField: undefined,
    remoteIdField: "id",
    lastSyncedAtField: undefined,
  }),
  createRegistryItem({
    tableName: "audit_events",
    entityName: "AuditEvent",
    scopeField: "account_remote_id",
    dependsOn: ["accounts"],
    conflictPolicy: SyncConflictPolicy.ClientWins,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
  }),
  createRegistryItem({
    tableName: "bill_photos",
    entityName: "BillPhoto",
    scopeField: "account_remote_id",
    dependsOn: ["billing_documents"],
    conflictPolicy: SyncConflictPolicy.ClientWins,
    tombstonePolicy: SyncTombstonePolicy.SoftDelete,
    isFinancialRecord: false,
    isWorkflowAggregate: false,
  }),
] as const;

export const syncRegistryByTable = new Map(
  syncRegistry.map((item) => [item.tableName, item]),
);

export const getSyncRegistryItem = (
  tableName: string,
): SyncRegistryItem | null => {
  return syncRegistryByTable.get(tableName) ?? null;
};

export const getSyncDependencyRank = (tableName: string): number => {
  const index = syncDependencyOrder.indexOf(
    tableName as (typeof syncDependencyOrder)[number],
  );

  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
};

export const getConflictPolicyForTable = (
  tableName: string,
): SyncConflictPolicyValue => {
  return (
    getSyncRegistryItem(tableName)?.conflictPolicy ??
    SyncConflictPolicy.ManualReview
  );
};
